### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by morrisrob** [koajs/multer#48]
## Bug Report

**Current Behavior**
"Error: Cannot find module 'multer'" after updating to 3.0.2.  Prior to updating koa/multer, I was using v3.0.0 without any issues.  We use webpack for bundling.  It looks like the issue has to do with webpack and the use of `fix-esm` which was introduced in v3.0.2.  Any thoughts / ideas on how to get this working?  Thanks!

**Environment**
- Node/npm/yarn version: Node 12  yarn v3.1.1
- @koa/multer & koa version: @koa/multer 3.0.2

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/51250711/204837496-4a847b24-8163-4c41-828f-59c27d5a7d8e.png)

**Comment by brogeby** [comment]
@saveman71 
@morrisrob 
Do you have multer installed seperately?

**Comment by 3imed-jaberi** [comment]
I have checked the module with both module formats (ESM and CJS), and there's no problem with the module.
As @brogeby mentioned, make sure to install 'multer' separately.

> You can check the example in 'README.md' and don't forget to install the modules.

**Comment by shellscape** [comment]
@titanism why are you closing issues without a resolution? There are now two issues closed that are resolved by an open and unreviewed PR. this one, #51 and #52 should all be open. This is incredibly frustrating.
